package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"bookmyvenue/graph/model"
	"bookmyvenue/internal/domain"
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// ApproveVenue
func (r *mutationResolver) ApproveVenue(ctx context.Context, id string) (bool, error) {
	venueID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid venue id format: %w", err)
	}
	if err := r.AdminVenueSvc.ApproveVenue(venueID); err != nil {
		return false, err
	}
	return true, nil
}

// RejectVenue
func (r *mutationResolver) RejectVenue(ctx context.Context, id string, reason string) (bool, error) {
	venueID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid venue id format: %w", err)
	}
	if err := r.AdminVenueSvc.RejectVenue(venueID, reason); err != nil {
		return false, err
	}
	return true, nil
}

// SuspendUser
func (r *mutationResolver) SuspendUser(ctx context.Context, id string) (bool, error) {
	userID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid user id format: %w", err)
	}
	var user domain.User
	if err := r.DB.WithContext(ctx).First(&user, "id = ?", userID).Error; err != nil {
		return false, fmt.Errorf("user not found: %w", err)
	}
	newStatus := "suspended"
	if user.Status == "suspended" {
		newStatus = "active"
	}
	if err := r.DB.WithContext(ctx).Model(&user).Update("status", newStatus).Error; err != nil {
		return false, fmt.Errorf("failed to update user status: %w", err)
	}
	return true, nil
}

// DashboardStats
func (r *queryResolver) DashboardStats(ctx context.Context) (*model.DashboardStats, error) {
	var totalVenues int64
	var pendingVenues int64
	var totalBookings int64
	var totalRevenue float64
	// 1. Total Venues
	r.DB.WithContext(ctx).Model(&domain.Venue{}).Count(&totalVenues)
	// 2. Pending Venues
	r.DB.WithContext(ctx).Model(&domain.Venue{}).Where("status = ?", "pending").Count(&pendingVenues)
	// 3. Total Bookings
	r.DB.WithContext(ctx).Model(&domain.Booking{}).Count(&totalBookings)
	// 4. Total Platform Revenue (Sum of all captured payments)
	r.DB.WithContext(ctx).Model(&domain.Payment{}).Where("status = ?", "captured").Select("COALESCE(SUM(amount), 0)").Scan(&totalRevenue)
	return &model.DashboardStats{
		TotalVenues:   int(totalVenues),
		TotalBookings: int(totalBookings),
		TotalRevenue:  totalRevenue,
		PendingVenues: int(pendingVenues),
	}, nil
}

// Venues
func (r *queryResolver) Venues(ctx context.Context, status *string) ([]*model.AdminVenue, error) {
	var venues []domain.Venue
	query := r.DB.WithContext(ctx).Model(&domain.Venue{})
	if status != nil && *status != "" {
		query = query.Where("status = ?", *status)
	}
	if err := query.Order("created_at DESC").Find(&venues).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch venues: %w", err)
	}
	results := make([]*model.AdminVenue, len(venues))
	for i, v := range venues {
		results[i] = &model.AdminVenue{
			ID:        v.ID.String(),
			Name:      v.Name,
			City:      v.City,
			Status:    v.Status,
			Address:   v.Address,
			CreatedAt: v.CreatedAt.Format(time.RFC3339),
		}
	}
	return results, nil
}

// Users
func (r *queryResolver) Users(ctx context.Context, role *string) ([]*model.AdminUser, error) {
	var users []domain.User
	query := r.DB.WithContext(ctx).Model(&domain.User{})
	if role != nil && *role != "" {
		query = query.Where("role = ?", *role)
	}
	if err := query.Order("created_at DESC").Find(&users).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch users: %w", err)
	}
	results := make([]*model.AdminUser, len(users))
	for i, u := range users {
		results[i] = &model.AdminUser{
			ID:           u.ID.String(),
			Name:         u.Name,
			Email:        u.Email,
			Role:         u.Role,
			Status:       u.Status,
			Phone:        u.Phone,
			BusinessName: u.BusinessName,
			GstNumber:    u.GSTNumber,
			CreatedAt:    u.CreatedAt.Format(time.RFC3339),
		}
	}
	return results, nil
}

// Bookings
func (r *queryResolver) Bookings(ctx context.Context, status *string) ([]*model.AdminBooking, error) {
	var bookings []domain.Booking
	query := r.DB.WithContext(ctx).Model(&domain.Booking{})
	if status != nil && *status != "" {
		query = query.Where("status = ?", *status)
	}
	if err := query.Order("created_at DESC").Find(&bookings).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch bookings: %w", err)
	}
	results := make([]*model.AdminBooking, len(bookings))
	for i, b := range bookings {
		results[i] = &model.AdminBooking{
			ID:          b.ID.String(),
			UserID:      b.UserID.String(),
			SpaceID:     b.SpaceID.String(),
			TotalAmount: b.TotalAmount,
			AmountPaid:  b.AmountPaid,
			Status:      b.Status,
			CreatedAt:   b.CreatedAt.Format(time.RFC3339),
		}
	}
	return results, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
