// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AdminBooking struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userId"`
	SpaceID     string  `json:"spaceId"`
	TotalAmount float64 `json:"totalAmount"`
	AmountPaid  float64 `json:"amountPaid"`
	Status      string  `json:"status"`
	CreatedAt   string  `json:"createdAt"`
}

type AdminUser struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Email        string  `json:"email"`
	Role         string  `json:"role"`
	Status       string  `json:"status"`
	Phone        *string `json:"phone,omitempty"`
	BusinessName *string `json:"businessName,omitempty"`
	GstNumber    *string `json:"gstNumber,omitempty"`
	CreatedAt    string  `json:"createdAt"`
}

type AdminVenue struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	City      string `json:"city"`
	Status    string `json:"status"`
	Address   string `json:"address"`
	CreatedAt string `json:"createdAt"`
}

type DashboardStats struct {
	TotalVenues   int     `json:"totalVenues"`
	TotalBookings int     `json:"totalBookings"`
	TotalRevenue  float64 `json:"totalRevenue"`
	PendingVenues int     `json:"pendingVenues"`
}

type Mutation struct {
}

type Query struct {
}
